import { FoodItem } from './types';

export const foodDatabase: FoodItem[] = [
  { id: 'f1', name: 'Chicken Breast', category: 'Protein', calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  { id: 'f2', name: 'White Rice', category: 'Grains', calories: 130, protein: 2.7, carbs: 28, fat: 0.3 },
  { id: 'f3', name: 'Eggs', category: 'Protein', calories: 155, protein: 13, carbs: 1.1, fat: 11 },
  { id: 'f4', name: 'Banana', category: 'Fruits', calories: 89, protein: 1.1, carbs: 23, fat: 0.3 },
  { id: 'f5', name: 'Apple', category: 'Fruits', calories: 52, protein: 0.3, carbs: 14, fat: 0.2 },
  { id: 'f6', name: 'Whole Wheat Bread', category: 'Grains', calories: 247, protein: 13, carbs: 41, fat: 3.4 },
  { id: 'f7', name: 'Oatmeal', category: 'Grains', calories: 68, protein: 2.4, carbs: 12, fat: 1.4 },
  { id: 'f8', name: 'Salmon', category: 'Protein', calories: 208, protein: 20, carbs: 0, fat: 13 },
  { id: 'f9', name: 'Broccoli', category: 'Vegetables', calories: 34, protein: 2.8, carbs: 7, fat: 0.4 },
  { id: 'f10', name: 'Milk (Whole)', category: 'Dairy', calories: 61, protein: 3.2, carbs: 4.8, fat: 3.3 },
  { id: 'f11', name: 'Greek Yogurt', category: 'Dairy', calories: 59, protein: 10, carbs: 3.6, fat: 0.4 },
  { id: 'f12', name: 'Pasta', category: 'Grains', calories: 131, protein: 5, carbs: 25, fat: 1.1 },
  { id: 'f13', name: 'Potato', category: 'Vegetables', calories: 77, protein: 2, carbs: 17, fat: 0.1 },
  { id: 'f14', name: 'Sweet Potato', category: 'Vegetables', calories: 86, protein: 1.6, carbs: 20, fat: 0.1 },
  { id: 'f15', name: 'Avocado', category: 'Fruits', calories: 160, protein: 2, carbs: 9, fat: 15 },
  { id: 'f16', name: 'Almonds', category: 'Nuts', calories: 579, protein: 21, carbs: 22, fat: 50 },
  { id: 'f17', name: 'Beef (Ground)', category: 'Protein', calories: 250, protein: 26, carbs: 0, fat: 15 },
  { id: 'f18', name: 'Turkey Breast', category: 'Protein', calories: 135, protein: 30, carbs: 0, fat: 1 },
  { id: 'f19', name: 'Tuna', category: 'Protein', calories: 132, protein: 28, carbs: 0, fat: 1.3 },
  { id: 'f20', name: 'Spinach', category: 'Vegetables', calories: 23, protein: 2.9, carbs: 3.6, fat: 0.4 },
  { id: 'f21', name: 'Carrots', category: 'Vegetables', calories: 41, protein: 0.9, carbs: 10, fat: 0.2 },
  { id: 'f22', name: 'Tomato', category: 'Vegetables', calories: 18, protein: 0.9, carbs: 3.9, fat: 0.2 },
  { id: 'f23', name: 'Orange', category: 'Fruits', calories: 47, protein: 0.9, carbs: 12, fat: 0.1 },
  { id: 'f24', name: 'Peanut Butter', category: 'Nuts', calories: 588, protein: 25, carbs: 20, fat: 50 },
  { id: 'f25', name: 'Quinoa', category: 'Grains', calories: 120, protein: 4.4, carbs: 21, fat: 1.9 },
  { id: 'f26', name: 'Lentils', category: 'Legumes', calories: 116, protein: 9, carbs: 20, fat: 0.4 },
  { id: 'f27', name: 'Tofu', category: 'Protein', calories: 76, protein: 8, carbs: 1.9, fat: 4.8 },
  { id: 'f28', name: 'Brown Rice', category: 'Grains', calories: 112, protein: 2.6, carbs: 24, fat: 0.9 },
  { id: 'f29', name: 'Cottage Cheese', category: 'Dairy', calories: 98, protein: 11, carbs: 3.4, fat: 4.3 },
  { id: 'f30', name: 'Honey', category: 'Sweeteners', calories: 304, protein: 0.3, carbs: 82, fat: 0 },
  { id: 'f31', name: 'Olive Oil', category: 'Fats', calories: 884, protein: 0, carbs: 0, fat: 100 },
  { id: 'f32', name: 'Dark Chocolate', category: 'Snacks', calories: 546, protein: 5, carbs: 60, fat: 31 },
  { id: 'f33', name: 'Green Beans', category: 'Vegetables', calories: 31, protein: 1.8, carbs: 7, fat: 0.1 },
  { id: 'f34', name: 'Corn', category: 'Vegetables', calories: 86, protein: 3.2, carbs: 19, fat: 1.2 },
  { id: 'f35', name: 'Mushrooms', category: 'Vegetables', calories: 22, protein: 3.1, carbs: 3.3, fat: 0.3 },
  { id: 'f36', name: 'Cucumber', category: 'Vegetables', calories: 15, protein: 0.7, carbs: 3.6, fat: 0.1 },
  { id: 'f37', name: 'Lettuce', category: 'Vegetables', calories: 15, protein: 1.4, carbs: 2.9, fat: 0.2 },
  { id: 'f38', name: 'Watermelon', category: 'Fruits', calories: 30, protein: 0.6, carbs: 8, fat: 0.2 },
  { id: 'f39', name: 'Strawberry', category: 'Fruits', calories: 32, protein: 0.7, carbs: 8, fat: 0.3 },
  { id: 'f40', name: 'Mango', category: 'Fruits', calories: 60, protein: 0.8, carbs: 15, fat: 0.4 },
  { id: 'f41', name: 'Shrimp', category: 'Protein', calories: 99, protein: 24, carbs: 0.2, fat: 0.3 },
  { id: 'f42', name: 'Ham', category: 'Protein', calories: 145, protein: 21, carbs: 1.5, fat: 5.5 },
  { id: 'f43', name: 'Cheese (Cheddar)', category: 'Dairy', calories: 403, protein: 25, carbs: 1.3, fat: 33 },
  { id: 'f44', name: 'Butter', category: 'Fats', calories: 717, protein: 0.9, carbs: 0.1, fat: 81 },
  { id: 'f45', name: 'Blueberries', category: 'Fruits', calories: 57, protein: 0.7, carbs: 14, fat: 0.3 },
  { id: 'f46', name: 'Chickpeas', category: 'Legumes', calories: 164, protein: 8.9, carbs: 27, fat: 2.6 },
  { id: 'f47', name: 'Pineapple', category: 'Fruits', calories: 50, protein: 0.5, carbs: 13, fat: 0.1 },
  { id: 'f48', name: 'White Bread', category: 'Grains', calories: 265, protein: 9, carbs: 49, fat: 3.2 },
  { id: 'f49', name: 'Yogurt (Plain)', category: 'Dairy', calories: 61, protein: 3.5, carbs: 4.7, fat: 3.3 },
  { id: 'f50', name: 'Granola', category: 'Grains', calories: 489, protein: 15, carbs: 64, fat: 20 },
];
